- name: Change root password
  user: name=root password="{{ root_user_password }}"

- name: Add a deployment user
  user: name={{ deployment_user }} shell=/bin/bash password={{ deployment_user_password }} groups=sudo append=yes

- name: Add ssh key for deployment user
  user: name={{ deployment_user }} generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

- name: Add ssh user keys
  authorized_key: user={{ deployment_user }} key="{{ item.public_key }}"
  with_items: authorized_keys

- name: Some software should be installed
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items: base_install_packages

- name: Upgrade existing packages
  apt: upgrade=full

- name: Set language
  lineinfile:
    dest=/etc/environment
    state=present
    line='{{ item }}'
  with_items:
    - "LC_ALL={{lang}}"
    - "LANG={{lang}}"

- name: Set timezone variables
  copy: content='{{ timezone }}\n'
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
