- name: Add a deployment user
  user: name={{ deployment_user }} shell=/bin/bash password={{ deployment_user_password }} groups=sudo append=yes

- name: Add ssh key for deployment user
  user: name={{ deployment_user }} generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

- name: Add ssh user keys
  authorized_key: user={{ deployment_user }} key="{{ item.public_key }}"
  with_items: authorized_keys

- name: Some software should be installed
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - sudo
    - openssh-server
    - ntp
    - ssh
    - vim
    - locate
    - debian-keyring
    - debian-archive-keyring
    - ca-certificates
    - language-pack-en
    - language-pack-UTF-8

- name: Set timezone variables
  copy: content='{{ timezone }}\n'
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
